### ISSUE TITLE
Game Over screen with score only displayed on host

### ISSUE THREAD

**Issue by qwc** [Terasology/LightAndShadow#108]
In the Teracon 2019 multiplayer playtest we found out that the Game Over screen with the score is only displayed at the host of the game and the client could still walk around and shoot.

**Comment by skaldarnar** [comment]
In today's play-test all the clients were able to see the game over screen when connected a headless server.

![image](https://user-images.githubusercontent.com/1448874/89108268-37a3e880-d437-11ea-9a43-ede8b1ae9ffe.png)
