### ISSUE TITLE
Flora Art Assets

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#11]
Rather than the standard flowers currently present in the game we could create custom flavourful flowers representing the [4 different suits of cards](https://en.wikipedia.org/wiki/Suit_%28cards%29) as flowers. This might also include some appropriately colored grass types.
##

**Comment by dacharya64** [comment]
Looking at the current state of the module, it looks like the Diamonds and Clubs flora assets still need to be done. Is that correct? If so I can work on that.

**Comment by Cervator** [comment]
I believe so, yes. You may also want to go through the L&S thread in the art forum. It is pretty long - lots of forgotten stuff in there :-)

Also issues/PRs over in LightAndShadowResources just in case

**Comment by dacharya64** [comment]
Made a PR for this at https://github.com/Terasology/LightAndShadowResources/pull/22

**Comment by Cervator** [comment]
Closing this as completed by https://github.com/Terasology/LightAndShadowResources/pull/22 - thanks @dacharya64 ! 

While we could still add grasses and other things we've got a pretty decent set now and some other artwork requesting issues so it seems fair to close this with the expectation to see more like it in the future :-)
