### ISSUE TITLE
Flora Generator

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#12]
A flora generator to use the custom L&S flora art assets requested in #11 is nice to have and should be a fairly simple modification to a similar system in the Core module, modified to use L&S-specific blocks.  See MovingBlocks/Terasology#544 for some legacy discussion on the subject.
##

**Comment by rzats** [comment]
_From @Tuxacker on June 17, 2013 13:34_

I would make the Flora Generator more flexible by adding custom flower generation with a json file in the mod that describes all flora types which should be added and in which biomes / with which probability they should be added instead of cloning it. I could possibly do that, but i don't quite understand the mod data loading mechanics. Also this project is new to me, so i'm sorry in advance if I misunderstood something.

**Comment by rzats** [comment]
_From @skaldarnar on June 17, 2013 17:20_

Pinging @immortius for mod loading mechanics. Also, make sure to check out the forums: 
http://forum.movingblocks.net

**Comment by rzats** [comment]
_From @Cervator on June 17, 2013 17:52_

Talked to @Tuxacker some on IRC, idea boils down to the following rough outline:

1) Define a new asset type - [module]/worldgen/flora.json
2) Have engine scan for the new asset type
3) If found feed a list of plants from the flora.json to the FloraGenerator when running with that module active

@immortius - question then would be if you have any hints on how / where to do that or any links that might be helpful, or alternatively a better approach if you can think of any :-)

**Comment by rzats** [comment]
_From @immortius on June 17, 2013 22:39_

I would suggest the following over an asset:
 
1. Using block categories.  Flora could be given a flora category and biome categories.  This is a little crude but is simple and open for mods adding new flora.

2. Add a Flora list component and then create an entity prefab or prefabs with the component. This saves creating a whole new asset type. Mods can introduce new lists.

3. Add a flora component and give each flora block a prefab with it.  This can be used to add whatever generation information is needed to the blocks.
This is a little awkward at the moment without inline prefab support in block definitions.

While I've started working towards custom asset support in mods it isn't ready yet, and even then I'd suggest an entity system aligned approach where possible.

**Comment by Cervator** [comment]
Closing as completed by #62 !
