### ISSUE TITLE
Red Pawn Art Assets

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#14]
Need the right files for the Red Pawn in the right places 🙂 Based on an oreon miniion we need:
- [x] Animation in .md5anim format.
- [ ] Materials file in a .mat file format. This is one of our simple file/asset (text) formats that references the texture png.
- [ ] Prefab that ties everything together.
- [x] Skeletal mesh in .md5mesh format - the model itself.
- [x] Texture png - the UV mapping thing that gives the model its skin.

Some working placeholders with minimal content are present in https://github.com/Terasology/LightAndShadowResources/tree/master/assets as a simple example. If left as "oreon" in the prefab's Spawnable, a placed "portal" will spawn the creature occasionally.
##

**Comment by skaldarnar** [comment]
Done, assets can be found in 
- https://github.com/Terasology/LightAndShadowResources/tree/develop/assets/skeletalMesh
- https://github.com/Terasology/LightAndShadowResources/tree/develop/assets/textures/pieces
