### ISSUE TITLE
remove the mini map from LightAndShadow

### ISSUE THREAD

**Issue by stefaniamak** [Terasology/LightAndShadow#164]
## Description

We have concluded that it is best for the user to not know the information provided by the map in this module, thus it is best to remove it altogether.

### The map is located at the top left corner, as showcased by the following screenshot:
![image](https://user-images.githubusercontent.com/48293545/94610447-fb5efe00-02a8-11eb-863d-e73da90c3ead.png)

## ToDo

- [x] remove mini-map from the HUD (heads up display) of the module
- [x] remove any remaining code according to mini-map from LAS 

(both are pretty much the same task)

**Comment by arrwhidev** [comment]
I'll take a stab at this!

**Comment by skaldarnar** [comment]
This was done in #168

**Comment by jdrueckert** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove Minimap](https://trello.com/c/fXJoECmf/40-remove-minimap)
