### ISSUE TITLE
Carrom Corners decorative blocks

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#19]
A simple textured floor decoration for the "Carrom Corner" section of the map (see the star in the middle). The buildings could be implemented by simply placing red/black blocks (though these are also a WIP 😛)

Reference: https://forum.terasology.org/attachments/map-png.1021/

**Comment by skaldarnar** [comment]
We're currently not focusing on the bigger biome ideas. Closing this issue (for now), but we might reuse this for different arena maps based on the original art direction.
