### ISSUE TITLE
Pachisi Planes central Tao symbol

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#20]
While we need the plain red/block blocks for the floor (easy) we should have something special in the center, as it might double as the roof of the secret room holding the white wand. Rather than the diamond square on the map (http://forum.movingblocks.net/attachments/map-png.1021/) I propose we shape a large red/black tao on the ground with textured blocks (at least 20x20, maybe bigger?)

It might be doable with straight up square full-color blocks but some diagonal two color blocks might help, if not outright circle pieces (still all in flat blocks, no special shapes needed).

A partial implementation of the issue is available at https://github.com/Terasology/LightAndShadowResources/tree/YinYang.
##

**Comment by mdj117** [comment]
![screen shot 2017-01-12 at 12 41 53 pm](https://cloud.githubusercontent.com/assets/16411499/21880722/7e17232e-d8c6-11e6-9fe2-8550a8f6e931.png)
