### ISSUE TITLE
Secret room grand Tao 3d decorative animated model

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#21]
Something that would look _awesome_ as an animated model floating in the air a few blocks above the white wand:

![3dtao](https://f.cloud.github.com/assets/1063833/652323/5760d7cc-d49f-11e2-9a5a-ff5efe6a2712.gif)

Naturally it would be black/red instead. Maybe a custom model roughtly 3x3x3 in size that is fully animated like the gif?
##

**Comment by Cervator** [comment]
We actually got this floating around in a branch: https://github.com/Terasology/LightAndShadowResources/tree/YinYang

Haven't tried it for a while, but we might just need to dust it off, make sure it works, maybe tweak at the dimensions, and merge the branch.

**Comment by skaldarnar** [comment]
The arena has a central area resembling such a Tao symbol (we call it "yin yang" in code and assets). I think we have such a 3D model lingering around somewhere.
I'm closing this issue as the decorative part is somewhat fulfilled in the current state.
