### ISSUE TITLE
Collection quests

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#24]
Basic starter quests simply consisting of the traditional "go fetch me 10 x!" in this case likely minerals, flowers (#11), or blocks from the assorted "trees"

Completion should be acquiring enough of block x then returning to a location. Reward should be spawning some friendly NPCs (later on we can get fancier and have more of a "tech tree" that could also give bonuses and so on)
##

**Comment by skaldarnar** [comment]
We're focusing on making Light and Shadow some kind of "arena shooter" game mode. Such fetch quests fit more into the roadmap of Metal Renegades (which, in theory, already has these kinds of quests). 

Closing this issue as no longer relevant for LaS.
