### ISSUE TITLE
game crashes when we try to kill the player by spear

### ISSUE THREAD

**Issue by ujjman** [Terasology/LightAndShadow#251]
While playing LaS, if we try to kill the player using `spear`, a NPE occurs and crashes the game.

**Steps to Reproduce**
1. Start the game in multiplayer mode
2. Reduce the health of the other player using any weapon (do not make the health 0)
3. Now, use `spear` weapon to reduce the health of other player to 0 and NPE will occur, crashing the game

![e7](https://user-images.githubusercontent.com/49057926/143854642-86256823-1841-4820-a06e-8d1422813326.png)
![e8](https://user-images.githubusercontent.com/49057926/143854653-78ea6e9f-ebac-4350-a47d-e87bbf0a0d2b.png)

**Comment by jdrueckert** [comment]
Fixed by #254
