### ISSUE TITLE
Black Knight Art Assets

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#26]
Another model that is effectively done but needs to be exported and checked in sometime :-)

model and texture done, skeleton probably need to be redone, needs animations
##

**Comment by skaldarnar** [comment]
Done, assets can be found in 
- https://github.com/Terasology/LightAndShadowResources/tree/develop/assets/skeletalMesh
- https://github.com/Terasology/LightAndShadowResources/tree/develop/assets/textures/pieces
