### ISSUE TITLE
Red Queen Art Assets

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#27]
OFF WITH THEIR HEADS!

![offwiththeirheads](https://f.cloud.github.com/assets/1063833/657657/26151cb4-d56c-11e2-94d9-5188b544f797.jpg)

This is already almost done by @glasz - see https://github.com/MovingBlocks/Terasology/issues/569 for details.
##

**Comment by skaldarnar** [comment]
Done, assets can be found in 
- https://github.com/Terasology/LightAndShadowResources/tree/develop/assets/skeletalMesh
- https://github.com/Terasology/LightAndShadowResources/tree/develop/assets/textures/pieces
