### ISSUE TITLE
Red Knight Art Assets

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#31]
Concept art in thread; model, texture and walk animations done by @glasz - needs weapons/tools and additional animations.

https://forum.terasology.org/threads/light-and-shadow.762
##

**Comment by skaldarnar** [comment]
Done, assets can be found in 
- https://github.com/Terasology/LightAndShadowResources/tree/develop/assets/skeletalMesh
- https://github.com/Terasology/LightAndShadowResources/tree/develop/assets/textures/pieces
