### ISSUE TITLE
Black Bishop Art Assets

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#36]
Concept art in thread - needs a model as well as tools and animations!

https://forum.terasology.org/threads/light-and-shadow.762

Was previously worked on by Basilix: https://forum.terasology.org/threads/light-and-shadow.762/page-9#post-8066
##

**Comment by skaldarnar** [comment]
Done, assets can be found in 
- https://github.com/Terasology/LightAndShadowResources/tree/develop/assets/skeletalMesh
- https://github.com/Terasology/LightAndShadowResources/tree/develop/assets/textures/pieces
