### ISSUE TITLE
Red Bishop Art Assets

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#37]
Concept art in thread - previously worked on by @glasz, still needs tools and animations!

https://forum.terasology.org/threads/light-and-shadow.762
##

**Comment by skaldarnar** [comment]
Done, assets can be found in 
- https://github.com/Terasology/LightAndShadowResources/tree/develop/assets/skeletalMesh
- https://github.com/Terasology/LightAndShadowResources/tree/develop/assets/textures/pieces
