### ISSUE TITLE
"Dice" catapult ammo Art Assets

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#38]
Pretty straight forward: A block that looks like a 6-sided die, with the appropriate number of dots per side ;-) Would be hilarious to base damage on the side of the die that hits the target, but let's not go crazy...

A dice block asset has been created for the [Add A Dice tutorial](https://github.com/Terasology/TutorialAssetSystem/wiki/Add-A-Dice) - it may be added to L&S using the assets at https://github.com/Terasology/LightAndShadowResources/tree/master/assets/textures.
##

**Comment by Cervator** [comment]
Completed by Terasology/LightAndShadowResources#10 - closing :-)

Now we just need the catapult!
