### ISSUE TITLE
"Gray" Flora Art Asset

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#43]
Idea to go with the "card suit color" flora blocks - an "unclaimed" version of the suit flowers that the player could tag with a tool of some sort to turn into flowers following their side, yielding some sort of benefit like territory claim / regeneration for nearby friendly.

Edit: There are existing faction-specific versions at https://github.com/Terasology/LightAndShadowResources/tree/master/assets/blockTiles/flora

**Comment by rzats** [comment]
Art assets created by 
https://github.com/Terasology/LightAndShadowResources/pull/7 - only need to hook them up in-game now 🙂

**Comment by Cervator** [comment]
Closing as completed by #62 !
