### ISSUE TITLE
Circuitry to help power turrets in towers

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#44]
Idea from earlier that the defense towers in L&S should be powered by natural power sources the player has to hook up to turret blocks in built-towers. Turrets should be able to vary in strength based on the quality of the power supply and players should be able to sabotage the power supply as well
##

**Comment by jdrueckert** [comment]
The current way how the [towers to be integrated into LaS](https://github.com/Terasology/LightAndShadow/issues/247) work is based on economy with power cores that power the towers. Accordingly, I'll close this issue.
