### ISSUE TITLE
Tower turret blocks

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#45]
Depends on https://github.com/MovingBlocks/Terasology/issues/590 which itself likely depends on multiplayer, but it is possible we can do the art assets early and at least pretend the blocks can shoot arrows in the meantime :-)

Idea is that these turret blocks will be placed by players in towers (possibly with a few initial towers placed in the world on startup) and be the main defense against enemy NPC waves.

The power of the turrets should be able to vary both on quality of materials (upgradeable) and the possible addition of an actual power system (#44)
##

**Comment by skaldarnar** [comment]
Closing in favor of https://github.com/Terasology/LightAndShadow/issues/247
