### ISSUE TITLE
Very basic growth sim

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#47]
This isn't meant to be a "fancy" growth simulator of any sort, but a simple "check for crops every minute or so then increment the growth stage" to go with the art assets in https://github.com/MovingBlocks/Terasology/issues/580.

Should be fairly straight forward. Could be done with the ES using GrowthComponents attached to the crops and a System checking anything with a growth component once in a while and adding another block of height. Not sure if that would cause too many entities. Or just one per crop type + next gen ES magic in the multiplayer branch to get all fitting blocks in a chunk?

Could also adapt the door / diamond ace for the multi-block approach so the whole thing breaks as once. Or alternatively the billboard check used to make grass "break" if the supporting block is broken. In theory you could possibly harvest only the top of the plant and leave the lower blocks in place?
##

**Comment by TheFlash98** [comment]
Hey I'd like to take this up, any good place to start at?

**Comment by jdrueckert** [comment]
From the current vision for LaS, crop growth is not relevant anymore. The maps are intentionally dynamically created but in themselves rather static throughout the rounds. Also, there is [GrowingFlora](https://github.com/Terasology/growingflora) which does what I guess is the desired feature here.
