### ISSUE TITLE
Player avatar

### ISSUE THREAD

**Issue by rzats** [Terasology/LightAndShadow#48]
Has a few possible solutions:
- @SuperSnark has mentioned working on an "Adventurer" concept that the player could spawn as (would need both the concept + work for new model)
- @glasz has offered to throw something temporary together
- We could just use one of the existing L&S pieces like the Red Fool

Either way we'd need to actually attach the player to said model. Player already has a placeholder model in the multiplayer branch.

Could also be nice to support skinning for the "default" player model. This wouldn't affect gameplay with set models like in L&S.
##

**Comment by skaldarnar** [comment]
Done, assets can be found in 
- https://github.com/Terasology/LightAndShadowResources/blob/develop/assets/textures/whitePawnPlayer.png
- https://github.com/Terasology/LightAndShadowResources/tree/develop/assets/skeletalMesh
