### ISSUE TITLE
Add Javadoc for PlayerDeathSystem

### ISSUE THREAD

**Issue by skaldarnar** [Terasology/LightAndShadow#84]
Follow up to https://github.com/Terasology/LightAndShadow/pull/82

Add Javadoc to https://github.com/Terasology/LightAndShadow/blob/master/src/main/java/org/terasology/ligthandshadow/componentsystem/controllers/PlayerDeathSystem.java

**Comment by darshan3** [comment]
Closing as completed in #83.
